"use client";

import { useEffect, useMemo, useState } from "react";
import { useScrollFrameSequence } from "../../hooks/useScrollFrameSequence";
import { createFrameSource, type FrameSource } from "../../lib/frame-sequence/frameLoader";
import frameManifest from "../../lib/frame-sequence/frame-manifest.json";

export interface ScrollFrameSequenceProps {
  desktopBasePath?: string; // default "/frames-desktop"
  mobileBasePath?: string; // default "/frames-mobile"
  padLength?: number; // frame_002.webp -> 3
  breakpoint?: number; // px, default 768
  /** Extra scroll px consumed per frame. ~14 gives a natural feel at 100+ frames. */
  scrollPxPerFrame?: number;
  /** Lerp rate per 60fps-equivalent tick, 0..1. Lower = smoother/laggier. */
  smoothing?: number;
  /** Parallel frame downloads on desktop. Mobile is capped lower automatically. */
  concurrency?: number;
  className?: string;
  /** Screen-reader description. If omitted, canvas is purely decorative. */
  ariaLabel?: string;
}

const MOBILE_MAX_CONCURRENCY = 3;

export default function ScrollFrameSequence({
  desktopBasePath = "/frames-desktop",
  mobileBasePath = "/frames-mobile",
  padLength = 3,
  breakpoint = 768,
  scrollPxPerFrame = 14,
  smoothing = 0.14,
  concurrency = 6,
  className,
  ariaLabel,
}: ScrollFrameSequenceProps) {
  const [isMobile, setIsMobile] = useState<boolean | null>(null);
  const [reducedMotion, setReducedMotion] = useState(false);

  useEffect(() => {
    const widthQuery = window.matchMedia(`(max-width: ${breakpoint}px)`);
    const motionQuery = window.matchMedia("(prefers-reduced-motion: reduce)");
    setIsMobile(widthQuery.matches);
    setReducedMotion(motionQuery.matches);

    const onWidthChange = (e: MediaQueryListEvent) => setIsMobile(e.matches);
    const onMotionChange = (e: MediaQueryListEvent) => setReducedMotion(e.matches);
    widthQuery.addEventListener("change", onWidthChange);
    motionQuery.addEventListener("change", onMotionChange);
    return () => {
      widthQuery.removeEventListener("change", onWidthChange);
      motionQuery.removeEventListener("change", onMotionChange);
    };
  }, [breakpoint]);

  // Built from the real frame numbers on disk (lib/frame-sequence/frame-manifest.json,
  // regenerated by scripts/generate-frame-manifest.mjs) — never assumes a contiguous
  // 1..N sequence, so index i always maps to a frame that actually exists.
  const source = useMemo<FrameSource | null>(() => {
    if (isMobile === null) return null;
    const frameNumbers = isMobile ? frameManifest.mobile : frameManifest.desktop;
    const basePath = isMobile ? mobileBasePath : desktopBasePath;
    return createFrameSource(basePath, frameNumbers, padLength);
  }, [isMobile, mobileBasePath, desktopBasePath, padLength]);

  // Weaker mobile CPUs stutter when juggling too many parallel decodes — cap it
  // regardless of connection speed, independent of the network-based cap in the hook.
  const effectiveConcurrency = isMobile ? Math.min(MOBILE_MAX_CONCURRENCY, concurrency) : concurrency;

  // Avoid a layout shift before we know viewport width / motion preference
  if (!source) return <div className={className} style={{ height: "100svh" }} />;

  // Respect prefers-reduced-motion: no pinning, no scrub — just a static representative frame
  if (reducedMotion) {
    const midFrame = Math.floor(source.frameCount / 2);
    return (
      // eslint-disable-next-line @next/next/no-img-element
      <img
        className={className}
        src={source.getUrl(midFrame)}
        alt={ariaLabel ?? ""}
        style={{ width: "100%", height: "100svh", objectFit: "cover", display: "block" }}
      />
    );
  }

  return (
    <ScrollFrameCanvas
      source={source}
      scrollPxPerFrame={scrollPxPerFrame}
      smoothing={smoothing}
      concurrency={effectiveConcurrency}
      className={className}
      ariaLabel={ariaLabel}
    />
  );
}

function ScrollFrameCanvas({
  source,
  scrollPxPerFrame,
  smoothing,
  concurrency,
  className,
  ariaLabel,
}: {
  source: FrameSource;
  scrollPxPerFrame: number;
  smoothing: number;
  concurrency: number;
  className?: string;
  ariaLabel?: string;
}) {
  const { containerRef, canvasRef, loadProgress, isFirstFrameReady, scrollHeightPx } = useScrollFrameSequence(
    source,
    scrollPxPerFrame,
    smoothing,
    concurrency
  );

  return (
    <div
      ref={containerRef}
      className={className}
      role={ariaLabel ? "img" : undefined}
      aria-label={ariaLabel}
      // 100svh = "small viewport height" — stays fixed while the iOS/Android URL bar
      // shows or hides, so the pinned section never jumps mid-scroll.
      style={{ position: "relative", height: `calc(100svh + ${scrollHeightPx}px)` }}
    >
      <div style={{ position: "sticky", top: 0, height: "100svh", overflow: "hidden", contain: "layout paint size" }}>
        <canvas ref={canvasRef} aria-hidden="true" style={{ width: "100%", height: "100%", display: "block" }} />
        {!isFirstFrameReady && (
          <div
            aria-hidden
            style={{
              position: "absolute",
              inset: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              background: "#000",
              color: "#fff",
              fontSize: 14,
              opacity: 0.6,
              pointerEvents: "none",
            }}
          >
            Loading {Math.round(loadProgress * 100)}%
          </div>
        )}
      </div>
    </div>
  );
}